---

- name: Install RHDH Application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'developer-hub/developer-hub-application.yaml.j2') }}"

- name: Apply extra RHDH application config
  kubernetes.core.k8s:
    namespace: "{{ ocp4_workload_platform_engineering_workshop_rhdh_namespace }}"
    state: present
    definition: "{{ lookup('file', 'app-config-rhdh.yaml') | from_yaml }}"

    